import { DailyLeadsCard } from '@/features/analytics/components/daily-leads-card';
import { AnalyticsProvider } from '@/features/analytics/provider';

// import { LeadsVolumeChart } from "@/features/analytics/components/leads-volume-chart"
// import { TopProductsList } from "@/features/analytics/components/top-products-list"
import { PageHeader } from '../_components/layout/page-header';

export default function LeadsPage() {
  return (
    <AnalyticsProvider>
      <div className="mx-auto w-full max-w-5xl min-w-0 space-y-6">
        <PageHeader title="Leads" subtitle="Track WhatsApp leads generated by AI assistant" />

        <div className="flex w-full min-w-0 flex-col gap-y-2">
          <DailyLeadsCard />
          {/* <LeadsVolumeChart /> */}
          {/* <TopProductsList /> */}
        </div>
      </div>
    </AnalyticsProvider>
  );
}
