import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { ThemeProvider } from "@repo/ui-core/components/theme-provider";
import { Toaster } from "@repo/ui-core/components/sonner";
import { TooltipProvider } from "@repo/ui-core/components/tooltip";

import "./globals.css";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={geist.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>{children}</TooltipProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
