import type { Metadata } from "next";
import {
  Geist,
  Noto_Sans_JP,
  Noto_Sans_Gurmukhi,
  Noto_Sans_Arabic,
} from "next/font/google";

import { ThemeProvider } from "@repo/ui-core/components/theme-provider";
import { Toaster } from "@repo/ui-core/components/sonner";
import { TooltipProvider } from "@repo/ui-core/components/tooltip";

import "./globals.css";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
});

const notoSansGurmukhi = Noto_Sans_Gurmukhi({
  subsets: ["latin"],
  variable: "--font-noto-sans-gurmukhi",
});

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["latin"],
  variable: "--font-noto-sans-arabic",
});
export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geist.variable} ${notoSansJP.variable} ${notoSansGurmukhi.variable} ${notoSansArabic.variable} ${geist.className}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <div className="relative flex min-h-screen flex-col">
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </TooltipProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
