import type { Metadata } from 'next';

import { SWRProvider } from '@/provider/swr-provider';
import '@/styles/globals.css';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/sonner';

import { fontVariables } from './fonts';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontVariables} suppressHydrationWarning>
      <body className="antialiased">
        <SWRProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <NuqsAdapter>{children}</NuqsAdapter>
            <Toaster position="top-center" />
          </ThemeProvider>
        </SWRProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
